import fs from "node:fs"
import path from "node:path"
import { createHash } from "node:crypto"
import react from "@vitejs/plugin-react"
import tailwindcss from "@tailwindcss/vite"
import { defineConfig, type Plugin } from "vite"

const STATIC_EXT = /\.(js|css|html|svg|ico|webmanifest|woff2?)$/i

/** Emits dist/sw.js that precaches build assets; API stays network-only. */
function punchbookServiceWorker(): Plugin {
  let outDir = path.resolve("dist")

  return {
    name: "punchbook-service-worker",
    apply: "build",
    configResolved(config) {
      outDir = path.resolve(config.root, config.build.outDir)
    },
    closeBundle() {
      const urls = new Set<string>(["/"])

      const walk = (dir: string, base = "") => {
        for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
          const rel = `${base}/${entry.name}`.replace(/\\/g, "/")
          const full = path.join(dir, entry.name)
          if (entry.isDirectory()) {
            walk(full, rel)
            continue
          }
          if (entry.name === "sw.js") continue
          if (STATIC_EXT.test(entry.name)) urls.add(rel)
        }
      }

      walk(outDir)

      const precache = [...urls].sort()
      const revision = createHash("sha1")
        .update(precache.join("\n"))
        .digest("hex")
        .slice(0, 8)

      const sw = `/* Generated by punchbook-service-worker — do not edit */
const CACHE_NAME = "punchbook-static-${revision}";
const PRECACHE_URLS = ${JSON.stringify(precache, null, 2)};

function isApiRequest(request, url) {
  if (request.method !== "GET" && request.method !== "HEAD") return true;
  if (url.origin !== self.location.origin) return true;
  if (url.pathname.includes("/graphql")) return true;
  return /^\\/(memberships|packages|dashboard|invoices|payos|webhooks|staffs|sessions|auth|login)/.test(
    url.pathname,
  );
}

function isStaticAsset(url) {
  return (
    url.pathname.startsWith("/assets/") ||
    /\\.(js|css|svg|ico|webmanifest|woff2?)$/i.test(url.pathname)
  );
}

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(CACHE_NAME)
      .then((cache) => cache.addAll(PRECACHE_URLS))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter((key) => key !== CACHE_NAME)
            .map((key) => caches.delete(key)),
        ),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  const url = new URL(request.url);

  if (isApiRequest(request, url)) return;

  if (isStaticAsset(url)) {
    event.respondWith(
      caches.match(request).then((cached) => {
        if (cached) return cached;
        return fetch(request).then((response) => {
          if (response.ok) {
            const copy = response.clone();
            void caches.open(CACHE_NAME).then((cache) => cache.put(request, copy));
          }
          return response;
        });
      }),
    );
    return;
  }

  if (request.mode === "navigate") {
    event.respondWith(
      fetch(request)
        .then((response) => {
          if (response.ok) {
            const copy = response.clone();
            void caches.open(CACHE_NAME).then((cache) => cache.put(request, copy));
          }
          return response;
        })
        .catch(() => caches.match("/") || caches.match("/index.html")),
    );
  }
});
`

      fs.writeFileSync(path.join(outDir, "sw.js"), sw)
    },
  }
}

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), tailwindcss(), punchbookServiceWorker()],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
})
