plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/graphql_controller.rb'
    - 'spec/**/*'

Naming/MethodParameterName:
  Exclude:
    - 'app/controllers/graphql_controller.rb'

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
